### ISSUE TITLE
Facebook: "Invalid App ID: None"

### ISSUE THREAD

**Issue by nurzhannogerbek** [cyface/django-socialprofile#9]
Hello! First of all I need to say **THANKS** for releasing, supporting and documenting this app!
I am really pumped to use it, just a little problem in the way cause I am new in Django.

I am tring to test your **DEMO app** to see how it looks like. Unfortunatly, right know I have problems in Sign In with Facebook and Twitter (didn`t test Google). What can you advice to me?! 

**My steps**:
1) I've registered my own apps and take API keys
2) In Facebook I set the site URL as `http://www.mysite.com:8000/` , also in Twitter I set the callback URL as `http://www.mysite.com:8000/socialprofile/socialauth/complete/twitter/`
3) I changed hosts file in OS as `127.0.0.1 www.mysite.com`
4) Then I edited settings_local_template.py file with that API keys.

**Facebook error:**
`Facebook: "Invalid App ID: None"`

**Twitter error:**

```
ValueError at /socialprofile/login/twitter/
Only unicode objects are escapable. Got None of type <class 'NoneType'>
```

**Comment by cyface** [comment]
Did you rename settings_local_template to settings_local?

**Comment by NogerbekNurzhan** [comment]
I forgot to rename. It works now but anyway with some problems.

**Twitter error:**
```
IntegrityError at /socialprofile/complete/twitter/
NOT NULL constraint failed: socialprofile_socialprofile.url
```
In Facebook I have strange **username** (rundom numbers), while in Twitter for instance in log I see normal username(сonnection of first_name+last_name). How can I fix it?

**Comment by cyface** [comment]
The twitter error is likely because you had a partial registration before
you got the settings working.  If you go into the Django Admin and delete
everything out of the social profile tables, that will reset you, and you
can give it another go.

For Facebook, that's a normal situation with username - it generates one
automatically, since Facebook uses email as username.  You can build a
screen to enable users to change their username if you'd like, or you can
use First Name / Last Name in your displays instead of username.  Part of
the Joy of Facebook! :)

**Comment by NogerbekNurzhan** [comment]
As you said I go into the Django and delete everything out of the "User Social Auths", then tried to sign in with twitter again. Unfortunatly I had the same problem as before, however in admin I can see information from twitter. Looks little bit strange for me and I have no idea how to fix it.

Let me ask you one more question. I have error in google: `The redirect URI in the request, http://www.mysite.com:8000/socialprofile/complete/google-oauth2/, does not match the ones authorized for the OAuth client`. I really comfused with this `Error: redirect_uri_mismatch` cause in google console in Authorized redirect URIs: `http://www.mysite.com:8000/socialauth/complete/google-oauth2/` So where I did mistake? What can you advice to me in this case?!

**Comment by cyface** [comment]
Hmm, not sure on your mismatch - you might check here:
http://stackoverflow.com/questions/11485271/google-oauth-2-authorization-error-redirect-uri-mismatch

**Comment by NogerbekNurzhan** [comment]
There are a lot of such questions in Stackoverflow but in most of them people just forger to add Authorized redirect URIs or did mistake in URL. It make me sad, anyway THANKS for your reply and let me know if you have any ideas about that problems! =)

**Comment by khizirsiddiqui** [comment]
In `http://www.mysite.com:8000/socialprofile/complete/google-oauth2/``` did you really user mysite.com or is it localhost or 127.0.0.1
I am just guessing. Maybe a minor mistake.

**Comment by cyface** [comment]
Yeah, you need to replace mysite.com with the name of the site that you set up to be authorized.

Some of the keys will let you use localhost or 127.0.0.1 for testing, but some require an actual domain name. That's why I used mysite.com as the example...


Tim
